spring: 
  profiles: 
    active: dev

---
spring: 
  profiles: dev
  application: 
    name: springcloud-config-dev


server: 
  port: 9000

eureka:
  instance:
    hostname: shadow7001.com #服务端的实例名称
  client:
    register-with-eureka: false #表示不向注册中心注册自己
    fetch-registry: false #为false 表示自己为注册中心
    service-url:  #注册地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://shadow7002.com:7002/eureka/,http://shadow7003.com:7003/eureka/
